version: '3'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    environment:
      - DATABASE_URL=sqlite:///./rmt_park.db
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload